rvm:
  - 2.2.3

before_install:
  - "gem install bundler"
addons:
  postgresql: "9.3"

node_js:
  - "0.10"

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - psql -c 'create database codesampa_test;' -U postgres
  - "bundle exec rake db:migrate"
  - npm install -g bower
  - bower install

env:
  - DISPLAY=:99.0

script:
  - "bundle exec rspec spec"

branches:
  only:
    - master

