rvm:
  - 2.2.3

before_install:
  - "gem install bundler"

before_script:
  - "cp config/database.sample.yml config/database.yml"
  - "psql -c 'create role codesampa SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database codesampa_test;' -U codesampa 123abc@"
  - "bundle exec rake db:migrate"

env:
  - DISPLAY=:99.0

script:
  - "bundle exec rspec spec"

branches:
  only:
    - master

